# Gateway API本体のCRDは事前にkubectlで手動apply済みであること
# (manifests/gateway/traefik-helmchartconfig.yaml内のコメント参照)。
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satsho/iac.git
    targetRevision: main
    path: manifests/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
