# keycloak-adminシークレットを事前に作成しておくこと(manifests/keycloak/deployment.yaml参照)。
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/satsho/iac.git
    targetRevision: main
    path: manifests/keycloak
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
